
# coding: utf-8

# In[ ]:



"""RRR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIR_sNnwW8mS-kTcFhp5nrwVRD0KkRok
"""

import requests
from bs4 import BeautifulSoup
import os
import smtplib, ssl
import sched, time
delay = 60

while(True):
    link= "https://in.bookmyshow.com/buytickets/rrr-hyderabad/movie-hyd-ET00094579-MT/202203"
    day= str(25)
    linkf= link+day
    print(linkf)


    r = requests.get(linkf)   
    soup = BeautifulSoup(r.content, 'html5lib')

    theatres_rrr={}  # a list to store theatres
    table = soup.find('ul', attrs = {'id':'venuelist'})

    for row in table.findAll("li", attrs = {'class':'list'}):
        if row['data-id'] == 'PVSF':
            if len(row.findAll("div", attrs = {'class':'showtime-pill-container'})) > 11:
                print("tickets available")
                port = 465  # For SSL
                smtp_server = "smtp.gmail.com"
                sender_email = "yagtester123@gmail.com"  # Enter your address
                receiver_email = "kviswanth96@gmail.com"  # Enter receiver address
                password = 'testingtesting'
                message = "movie tickets are now available"
                context = ssl.create_default_context()
                with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
                    server.login(sender_email, password)
                    server.sendmail(sender_email, receiver_email, message)
            else :
                print("Better luck next time")
            break
       
    time.sleep(30)

